apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: roboshop-cluster
  
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch"]

#to get api groups => kubectl get api-resources | grep per

---

apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "anilRBAC" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: roboshop-cluster
subjects:
- kind: Group
  name: anilRBAC # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: roboshop-cluster
  apiGroup: rbac.authorization.k8s.io
